#!/bin/bash

#Return library version in the libtool current:revision:age format.

#From http://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html:

# 1. Start with version information of .0:0:0. for each libtool
#    library.
# 2. Update the version information only immediately before a public
#    release of your software. More frequent updates are unnecessary, and
#    only guarantee that the current interface number gets larger faster.
# 3. If the library source code has changed at all since the last
#    update, then increment revision (.c:r:a. becomes .c:r+1:a.).
# 4. If any interfaces have been added, removed, or changed since the
#    last update, increment current, and set revision to 0.
# 5. If any interfaces have been added since the last public release,
#    then increment age.
# 6. If any interfaces have been removed or changed since the last
#    public release, then set age to 0.

# History:
# Spindle 0.9  - libspindlefe.so 0.0.0, libspindlebe.so 0.0.0, libspindle.so 0.0.0
# Spindle 0.10 - libspindlefe.so 1.0.1, libspindlebe.so 1.0.1, libspindle.so 0.1.0
# Spindle 0.11 - libspindlefe.so 2.0.0, libspindlebe.so 2.0.0, libspindle.so 0.1.0
# Spindle 0.12 - libspindlefe.so 2.1.0, libspindlebe.so 2.1.0, libspindle.so 0.1.0

if test "x$1" == "xspindlefe"; then
echo 2:1:0
fi
if test "x$1" == "xspindlebe"; then
echo 2:1:0
fi
if test "x$1" == "xlibspindle"; then
echo 0:1:0
fi
if test "x$1" == "xspindleslurm"; then
echo 0:0:0
fi
