version: "2.2"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
      
  slurmdbd:
    build:
      context: .
    command: "slurmdbd"
    container_name: slurmdbd
    hostname: slurmdbd
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - tmp_slurm:/tmp
      - ./sshd_config:/etc/ssh/sshd_config
    expose:
      - "6819"
      - "22"
    depends_on:
      - mysql

  slurmctld:
    build:
      context: .
    privileged: true
    command: "slurmctld"
    container_name: slurmctld
    hostname: slurmctld
    volumes_from:
      - slurmdbd
    expose:
      - "6817"
      - "22"
    depends_on:
      - "slurmdbd"

  c1:
    build:
      context: .
    command: "slurmd"
    privileged: true
    hostname: c1
    container_name: c1
    volumes_from:
      - slurmctld
    links:
      - slurmctld
    expose:
      - "6818"
      - "22"
    depends_on:
      - "slurmctld"

  c2:
    build:
      context: .
    command: "slurmd"
    privileged: true
    hostname: c2
    container_name: c2
    links:
      - slurmctld
    volumes_from:
      - slurmctld
    expose:
      - "6818"
      - "22"
    depends_on:
      - "slurmctld"
      
volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  tmp_slurm:
