#!/bin/bash

ID=SIERRA_36h_1
BMPATH=/g/g92/frings1/LLNL/pynamic/benchmark4
SYSTEM=cab
DO_NON_LDCS=NO
DO_LDCS=YES
BENCHNUMITER=1
BENCHNP=4
BENCHNUMSERVER=1
DEBUG_SERVER=NO
# NO,YES, ALL
DEBUG_CLIENT=NO
#BENCHTASKPERNODE=24
BENCHPRELOAD=${BMPATH}/file_preload.dat

ID=$ID \
BMPATH=$BMPATH \
SYSTEM=$SYSTEM \
DO_NON_LDCS=$DO_NON_LDCS \
DO_LDCS=$DO_LDCS \
BENCHNP=$BENCHNP \
BENCHNUMITER=$BENCHNUMITER \
BENCHNUMSERVER=$BENCHNUMSERVER \
DEBUG_SERVER=$DEBUG_SERVER \
DEBUG_CLIENT=$DEBUG_CLIENT \
BENCHTASKPERNODE=$BENCHTASKPERNODE \
BENCHPRELOAD=$BENCHPRELOAD \
./runit_multi_bm.sh