#!/bin/sh

if [ x$SPINDLE_TEST_ARGS = x ] ; then
PROCS=`flux resource info | tr ',' '\n' | grep Cores | awk '{print $1}'`
else
PROCS=$SPINDLE_TEST_ARGS
fi

flux run -o userrc=spindle.rc -o spindle -n $PROCS $*

