#!/bin/sh

echo Running: ./run_driver $*

cd TEST_RUN_DIR

export LD_LIBRARY_PATH=`pwd`
export SPINDLE_TEST=1
export LIBRARY_LIST="`pwd`/libcxxexceptA.so:`pwd`/libtest100.so:`pwd`/libtest2000.so:`pwd`/libtest500.so:`pwd`/libtest1000.so:`pwd`/libtest4000.so:`pwd`/libtest6000.so:`pwd`/libdepA.so:`pwd`/libtest10.so:`pwd`/libtest10000.so:`pwd`/libtest50.so:`pwd`/libtest8000.so"

export SPINDLE_BLUEGENE="BLUEGENE_TEST"
if test "x$SPINDLE_BLUEGENE" == "xfalse"; then
if [ $1 == --ldpreload ] ; then
export LD_PRELOAD="$LIBRARY_LIST"
fi
export SPINDLE_BGQ_LD_PRELOAD="false"
else
export SPINDLE_BGQ_LD_PRELOAD="true"
fi

if [ $1 == --dependency ] ; then
export TEST_EXEC=./test_driver_libs
elif [ $1 == --dlreopen ] ; then
export TEST_EXEC=./test_driver_libs
else
export TEST_EXEC=./test_driver
fi

if [ $2 == --preload ] ; then 
export SPINDLE_OPTS="--preload=preload_file_list"
fi
if [ $2 == --push ] ; then 
export SPINDLE_OPTS="--push"
fi
if [ $2 == --pull ] ; then 
export SPINDLE_OPTS="--pull"
fi

export SPINDLE=SPINDLE_EXEC

./run_driver_rm $TEST_EXEC $*

