#!/bin/sh

if [ x$SPINDLE_TEST_ARGS = x ] ; then
((PROCS=*$SLURM_CPUS_ON_NODE))
else
PROCS=$SPINDLE_TEST_ARGS
fi

$SPINDLE $SPINDLE_OPTS /g/g0/dahn/workspace/FLUX/ngrm/zmq-broker/wreck/wreckrun -n $PROCS $*
