#!/bin/sh

export SPINDLE_TEST_ARGS="$@"
export SPINDLE_BLUEGENE="BLUEGENE_TEST"

./run_driver --dependency --push
./run_driver --dlopen --push
./run_driver --dlreopen --push
./run_driver --reorder --push
./run_driver --partial --push
./run_driver --ldpreload --push

./run_driver --dependency --pull
./run_driver --dlopen --pull
./run_driver --dlreopen --pull
./run_driver --reorder --pull
./run_driver --partial --pull
./run_driver --ldpreload --pull

if test "x$SPINDLE_BLUEGENE" != "xtrue"; then
./run_driver --dependency --fork
./run_driver --dlopen --fork
./run_driver --dlreopen --fork
./run_driver --reorder --fork
./run_driver --partial --fork
./run_driver --ldpreload --fork
fi

if test "x$SPINDLE_BLUEGENE" != "xtrue"; then
./run_driver --dependency --forkexec
./run_driver --dlopen --forkexec
./run_driver --dlreopen --forkexec
./run_driver --reorder --forkexec
./run_driver --partial --forkexec
./run_driver --ldpreload --forkexec
fi

./run_driver --dependency --chdir
./run_driver --dlopen --chdir
./run_driver --dlreopen --chdir
./run_driver --reorder --chdir
./run_driver --partial --chdir
./run_driver --ldpreload --chdir

./run_driver --dependency --preload
./run_driver --dlopen --preload
./run_driver --dlreopen --preload
./run_driver --reorder --preload
./run_driver --partial --preload
./run_driver --ldpreload --preload

export SESSION_ID=`./run_driver --start-session`
./run_driver --dependency --session
./run_driver --dlopen --session
./run_driver --dlreopen --session
./run_driver --reorder --session
./run_driver --partial --session
./run_driver --ldpreload --session
./run_driver --end-session $SESSION_ID
unset SESSION_ID
