#ifndef LDCS_AUDIT_SERVER_STATELOOP_H
#define LDCS_AUDIT_SERVER_STATELOOP_H

typedef enum {
  LDCS_STATE_READY,
  LDCS_STATE_DONE,
  LDCS_STATE_CLIENT_INFO_MSG,
  LDCS_STATE_CLIENT_END_MSG,  
  LDCS_STATE_CLIENT_FILE_QUERY_MSG,
  LDCS_STATE_CLIENT_FILE_QUERY_EXACT_PATH_MSG,
  LDCS_STATE_CLIENT_FILE_QUERY_CHECK,
  LDCS_STATE_CLIENT_FORWARD_QUERY,
  LDCS_STATE_CLIENT_PROCESS_FILE,
  LDCS_STATE_CLIENT_PROCESS_DIR,
  LDCS_STATE_CLIENT_PROCESS_LOCAL_FILE_QUERY,
  LDCS_STATE_CLIENT_PROCESS_REJECTED_QUERY,
  LDCS_STATE_CLIENT_PROCESS_FULFILLED_QUERY,
  LDCS_STATE_CLIENT_PROCESS_NODIR_QUERY,
  LDCS_STATE_CLIENT_MYRANKINFO_MSG,
  LDCS_STATE_CLIENT_START_UPDATE,
  LDCS_STATE_CLIENT_UPDATE,
  LDCS_STATE_CLIENT_RECV_EXIT_BCAST,
  LDCS_STATE_UNKNOWN
} ldcs_state_t;

ldcs_state_t ldcs_server_process_state ( ldcs_process_data_t *ldcs_process_data, ldcs_message_t *msg, ldcs_state_t state );
char* _state_type_to_str (ldcs_state_t state);

#endif
